wip
Timo17100-c2c/delivery-carrier pull request #1
Opened 2019-05-29 10:22 UTC by bealdav

2019-06-12 09:43 UTC, yvaucher requested changes

2019-06-12 09:43 UTC, yvaucher commented on base_delivery_carrier_label/models/stock_picking.py
> +            "instead of generate_labels()")
What about a deprecation warning in the logs instead?

And call action_generate_carrier_label()

That way you can use the _logger defined after imports :)

2019-06-12 09:43 UTC, yvaucher commented on base_delivery_carrier_label/models/stock_picking.py
> +_logger = logging.getLogger(__name__)
Currently unused. (see comment about deprecation)

2019-06-12 17:16 UTC, bealdav commented
ping @yvaucher @florian-dacosta

2019-06-13 06:17 UTC, bealdav commented on base_delivery_carrier_label/views/stock.xml
> +                help="Create Shipping Label 🚚"
```suggestion
                help="Create Shipping Label 🚚"
                invisible="[('carrier_code', '=', False)]"
```

2019-06-13 09:04 UTC, yvaucher approved these changes
LGTM

I'm currious of how 🚚 displays in Odoo ^^

2019-06-13 09:09 UTC, bealdav commented
It'a the job of the browser not odoo

hihi http://www.unicode.org/emoji/charts/full-emoji-list.html#1f69a

only one byte and a lot of semantic ...  

Allow to not waste space in UI

2019-06-13 12:32 UTC, florian-dacosta reviewed
Just one remark because I don't get this part.

2019-06-13 12:32 UTC, florian-dacosta commented on base_delivery_carrier_label/models/stock_picking.py
> +                move_line.write({'result_package_id': move_line.package_id.id})
I don't understand this part...
Why write result_package_id if a move line with package id is found?
Seems very strange to me to have a package_id and a result_package_id with the same package on the same move line...
And I don't get why you have to do this and no simply something like this : 
`move_lines = picking.move_line_ids.filtered( lambda s: not (s.package_id or s.result_package_id))
if move_lines:
    package = self.env['stock.quant.package'].create({})
    move_lines.write({'result_package_id': package.id})
`

2019-06-13 13:50 UTC, florian-dacosta commented
:+1:

2019-06-13 15:03 UTC, angelmoya approved these changes
:+1:

2019-06-13 16:29 UTC, bealdav commented
This PR can be merged as it
but there is more here WIP
https://github.com/akretion/delivery-carrier/pull/125

2019-06-14 06:48 UTC, guewen commented
> only one byte and a lot of semantic ...

4 bytes actually 😬

2019-06-14 12:33 UTC, bealdav commented
ping Timo17100-c2c thanks for a review

2019-07-02 14:51 UTC, bealdav commented
@yvaucher, please could you merge it ?

Thanks

2019-07-04 13:15 UTC, yvaucher commented
@bealdav I don't have write access :-/

I'll do a take over of his PR and add your refactoring.

2019-07-04 13:49 UTC, bealdav commented
Thanks

2019-07-04 14:09 UTC, yvaucher commented
Included it in https://github.com/OCA/delivery-carrier/pull/205

Regarding the number of approval here, we probably can merge the whole thing.

2020-01-31 07:12 UTC, closed without merging